export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const SEE_ALL_QUESTIONS = "SEE_ALL_QUESTIONS";
export const ASK_A_QUESTION = "ASK_A_QUESTION";
export const COMMENT = "COMMENT";

export const SEE_ALL_USERS = "SEE_ALL_USERS";

export const SEND_MESSAGE="SEND_MESSAGE"
export const SEE_MESSAGE="SEE_MESSAGE"

